language: php
php:
  - 5.3
  - 5.4
install:
  # Install required dependencies
  - composer install
before_script:
  - mysql -e "CREATE DATABASE IF NOT EXISTS mydb CHARACTER SET utf8 COLLATE utf8_general_ci;" --user=root
  - mysql -e "GRANT ALL ON mydb.* TO 'myuser'@'localhost' IDENTIFIED BY 'mypass';" --user=root
  - mysql -e "CREATE DATABASE IF NOT EXISTS test CHARACTER SET utf8 COLLATE utf8_general_ci;" --user=root
  - mysql -e "GRANT ALL ON test.* TO 'myuser'@'localhost' IDENTIFIED BY 'mypass';" --user=root
  